project:
  type: website
  output-dir: docs

website:
  title: "My website"
  cookie-consent: false
  search: 
    location: navbar
    type: textbox
  navbar:
    title: false
    logo: "logo.jpg"
    logo-alt: "My logo"
    collapse: false

    left:
      - href: index.qmd
        text: Home
      - href: services.qmd
        text: Services
      - href: about.qmd
        text: About

    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ajgwords/
      - icon: mastodon
        href: https://social.vivaldi.net/@ajggeoger
      - icon: github
        href: https://github.com/ajgwords

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true